// Compiled by ClojureScript 0.0-2261
goog.provide('clustermap.components.full_report.overview');
goog.require('cljs.core');
goog.require('clustermap.formats.money');
goog.require('clustermap.formats.number');
goog.require('clustermap.formats.money');
goog.require('clustermap.formats.number');
goog.require('sablono.core');
goog.require('sablono.core');
goog.require('om.core');
goog.require('om.core');
clustermap.components.full_report.overview.describe_selection = (function describe_selection(p__36961){var map__36966 = p__36961;var map__36966__$1 = ((cljs.core.seq_QMARK_(map__36966))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__36966):map__36966);var value = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__36966__$1,cljs.core.constant$keyword$832);var type = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__36966__$1,cljs.core.constant$keyword$801);var pred__36967 = cljs.core._EQ_;var expr__36968 = type;if(cljs.core.truth_((pred__36967.cljs$core$IFn$_invoke$arity$2 ? pred__36967.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$886,expr__36968) : pred__36967.call(null,cljs.core.constant$keyword$886,expr__36968))))
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$948,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Total",cljs.core.constant$keyword$951,"Totals for the selected Portfolio Company"], null),cljs.core.constant$keyword$949,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Mean",cljs.core.constant$keyword$951,"Mean for the selected Portfolio Company"], null),cljs.core.constant$keyword$950,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Benchmark",cljs.core.constant$keyword$951,"Mean over all UK Companies"], null)], null);
} else
{if(cljs.core.truth_((pred__36967.cljs$core$IFn$_invoke$arity$2 ? pred__36967.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$887,expr__36968) : pred__36967.call(null,cljs.core.constant$keyword$887,expr__36968))))
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$948,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Total",cljs.core.constant$keyword$951,"Totals for the Portfolio Companies of the selected Investor"], null),cljs.core.constant$keyword$949,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Mean",cljs.core.constant$keyword$951,"Mean over the Portfolio Companies of the selected Investor"], null),cljs.core.constant$keyword$950,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Benchmark",cljs.core.constant$keyword$951,"Mean over all UK Companies"], null)], null);
} else
{if(cljs.core.truth_((pred__36967.cljs$core$IFn$_invoke$arity$2 ? pred__36967.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$889,expr__36968) : pred__36967.call(null,cljs.core.constant$keyword$889,expr__36968))))
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$948,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Total",cljs.core.constant$keyword$951,"Totals for the selected Constituency"], null),cljs.core.constant$keyword$949,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Mean",cljs.core.constant$keyword$951,"Mean over the Portfolio Companies with sites in the selected Constituency"], null),cljs.core.constant$keyword$950,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Benchmark",cljs.core.constant$keyword$951,"Mean over all UK Companies"], null)], null);
} else
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$948,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Total",cljs.core.constant$keyword$951,"Totals over all Portfolio Companies"], null),cljs.core.constant$keyword$949,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Mean",cljs.core.constant$keyword$951,"Mean over all Portfolio Companies"], null),cljs.core.constant$keyword$950,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$831,"Benchmark",cljs.core.constant$keyword$951,"Mean over all UK Companies"], null)], null);
}
}
}
});
clustermap.components.full_report.overview.overview_data = (function overview_data(p__36970){var map__36996 = p__36970;var map__36996__$1 = ((cljs.core.seq_QMARK_(map__36996))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__36996):map__36996);var selection_investment_stats = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__36996__$1,cljs.core.constant$keyword$952);var selection = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__36996__$1,cljs.core.constant$keyword$948);var all_investment_stats = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__36996__$1,cljs.core.constant$keyword$953);var sel_descrs = clustermap.components.full_report.overview.describe_selection(selection);var site_stats = (function (){var or__3543__auto__ = selection_investment_stats;if(cljs.core.truth_(or__3543__auto__))
{return or__3543__auto__;
} else
{return all_investment_stats;
}
})();return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$948,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$948.cljs$core$IFn$_invoke$arity$1(sel_descrs),cljs.core.PersistentHashMap.fromArrays([cljs.core.constant$keyword$954,cljs.core.constant$keyword$955,cljs.core.constant$keyword$947,cljs.core.constant$keyword$956,cljs.core.constant$keyword$957,cljs.core.constant$keyword$958,cljs.core.constant$keyword$959,cljs.core.constant$keyword$960,cljs.core.constant$keyword$961],[(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__36997 = site_stats;var G__36997__$1 = (((G__36997 == null))?null:cljs.core.constant$keyword$962.cljs$core$IFn$_invoke$arity$1(G__36997));var G__36997__$2 = (((G__36997__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__36997__$1));return G__36997__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__36997 = site_stats;var G__36997__$1 = (((G__36997 == null))?null:cljs.core.constant$keyword$962.cljs$core$IFn$_invoke$arity$1(G__36997));var G__36997__$2 = (((G__36997__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__36997__$1));return G__36997__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__36998 = site_stats;var G__36998__$1 = (((G__36998 == null))?null:cljs.core.constant$keyword$963.cljs$core$IFn$_invoke$arity$1(G__36998));return G__36998__$1;
})(),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__36998 = site_stats;var G__36998__$1 = (((G__36998 == null))?null:cljs.core.constant$keyword$963.cljs$core$IFn$_invoke$arity$1(G__36998));return G__36998__$1;
})(),cljs.core.constant$keyword$763,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__36999 = site_stats;var G__36999__$1 = (((G__36999 == null))?null:cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(G__36999));var G__36999__$2 = (((G__36999__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__36999__$1));return G__36999__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__36999 = site_stats;var G__36999__$1 = (((G__36999 == null))?null:cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(G__36999));var G__36999__$2 = (((G__36999__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__36999__$1));return G__36999__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__37000 = site_stats;var G__37000__$1 = (((G__37000 == null))?null:cljs.core.constant$keyword$964.cljs$core$IFn$_invoke$arity$1(G__37000));return G__37000__$1;
})(),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37000 = site_stats;var G__37000__$1 = (((G__37000 == null))?null:cljs.core.constant$keyword$964.cljs$core$IFn$_invoke$arity$1(G__37000));return G__37000__$1;
})(),cljs.core.constant$keyword$763,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__37001 = site_stats;var G__37001__$1 = (((G__37001 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37001));var G__37001__$2 = (((G__37001__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37001__$1));return G__37001__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37001 = site_stats;var G__37001__$1 = (((G__37001 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37001));var G__37001__$2 = (((G__37001__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37001__$1));return G__37001__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-")),(function (){var G__37002 = site_stats;var G__37002__$1 = (((G__37002 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37002));var G__37002__$2 = (((G__37002__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37002__$1));return G__37002__$2;
})(),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__37003 = site_stats;var G__37003__$1 = (((G__37003 == null))?null:cljs.core.constant$keyword$967.cljs$core$IFn$_invoke$arity$1(G__37003));return G__37003__$1;
})(),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37003 = site_stats;var G__37003__$1 = (((G__37003 == null))?null:cljs.core.constant$keyword$967.cljs$core$IFn$_invoke$arity$1(G__37003));return G__37003__$1;
})(),cljs.core.constant$keyword$763,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__37004 = site_stats;var G__37004__$1 = (((G__37004 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37004));var G__37004__$2 = (((G__37004__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37004__$1));return G__37004__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__37004 = site_stats;var G__37004__$1 = (((G__37004 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37004));var G__37004__$2 = (((G__37004__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37004__$1));return G__37004__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-")),(function (){var G__37005 = site_stats;var G__37005__$1 = (((G__37005 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37005));var G__37005__$2 = (((G__37005__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37005__$1));return G__37005__$2;
})()])], 0)),cljs.core.constant$keyword$949,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$949.cljs$core$IFn$_invoke$arity$1(sel_descrs),cljs.core.PersistentHashMap.fromArrays([cljs.core.constant$keyword$954,cljs.core.constant$keyword$955,cljs.core.constant$keyword$947,cljs.core.constant$keyword$956,cljs.core.constant$keyword$957,cljs.core.constant$keyword$958,cljs.core.constant$keyword$959,cljs.core.constant$keyword$960,cljs.core.constant$keyword$961],[(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__37006 = site_stats;var G__37006__$1 = (((G__37006 == null))?null:cljs.core.constant$keyword$962.cljs$core$IFn$_invoke$arity$1(G__37006));var G__37006__$2 = (((G__37006__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37006__$1));return G__37006__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37006 = site_stats;var G__37006__$1 = (((G__37006 == null))?null:cljs.core.constant$keyword$962.cljs$core$IFn$_invoke$arity$1(G__37006));var G__37006__$2 = (((G__37006__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37006__$1));return G__37006__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-")),"\u00A0",(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__37007 = site_stats;var G__37007__$1 = (((G__37007 == null))?null:cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(G__37007));var G__37007__$2 = (((G__37007__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37007__$1));return G__37007__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__37007 = site_stats;var G__37007__$1 = (((G__37007 == null))?null:cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(G__37007));var G__37007__$2 = (((G__37007__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37007__$1));return G__37007__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-")),"\u00A0",(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__37008 = site_stats;var G__37008__$1 = (((G__37008 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37008));var G__37008__$2 = (((G__37008__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37008__$1));return G__37008__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37008 = site_stats;var G__37008__$1 = (((G__37008 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37008));var G__37008__$2 = (((G__37008__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37008__$1));return G__37008__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-")),(function (){var G__37009 = site_stats;var G__37009__$1 = (((G__37009 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37009));var G__37009__$2 = (((G__37009__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37009__$1));return G__37009__$2;
})(),"\u00A0",(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__37010 = site_stats;var G__37010__$1 = (((G__37010 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37010));var G__37010__$2 = (((G__37010__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37010__$1));return G__37010__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__37010 = site_stats;var G__37010__$1 = (((G__37010 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37010));var G__37010__$2 = (((G__37010__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37010__$1));return G__37010__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-")),(function (){var G__37011 = site_stats;var G__37011__$1 = (((G__37011 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37011));var G__37011__$2 = (((G__37011__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37011__$1));return G__37011__$2;
})()])], 0)),cljs.core.constant$keyword$950,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$950.cljs$core$IFn$_invoke$arity$1(sel_descrs),cljs.core.PersistentHashMap.fromArrays([cljs.core.constant$keyword$954,cljs.core.constant$keyword$955,cljs.core.constant$keyword$947,cljs.core.constant$keyword$956,cljs.core.constant$keyword$957,cljs.core.constant$keyword$958,cljs.core.constant$keyword$959,cljs.core.constant$keyword$960,cljs.core.constant$keyword$961],[(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__37012 = all_investment_stats;var G__37012__$1 = (((G__37012 == null))?null:cljs.core.constant$keyword$962.cljs$core$IFn$_invoke$arity$1(G__37012));var G__37012__$2 = (((G__37012__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37012__$1));return G__37012__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37012 = all_investment_stats;var G__37012__$1 = (((G__37012 == null))?null:cljs.core.constant$keyword$962.cljs$core$IFn$_invoke$arity$1(G__37012));var G__37012__$2 = (((G__37012__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37012__$1));return G__37012__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__37013 = all_investment_stats;var G__37013__$1 = (((G__37013 == null))?null:cljs.core.constant$keyword$963.cljs$core$IFn$_invoke$arity$1(G__37013));return G__37013__$1;
})(),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37013 = all_investment_stats;var G__37013__$1 = (((G__37013 == null))?null:cljs.core.constant$keyword$963.cljs$core$IFn$_invoke$arity$1(G__37013));return G__37013__$1;
})(),cljs.core.constant$keyword$763,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__37014 = all_investment_stats;var G__37014__$1 = (((G__37014 == null))?null:cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(G__37014));var G__37014__$2 = (((G__37014__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37014__$1));return G__37014__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__37014 = all_investment_stats;var G__37014__$1 = (((G__37014 == null))?null:cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(G__37014));var G__37014__$2 = (((G__37014__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37014__$1));return G__37014__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__37015 = all_investment_stats;var G__37015__$1 = (((G__37015 == null))?null:cljs.core.constant$keyword$964.cljs$core$IFn$_invoke$arity$1(G__37015));return G__37015__$1;
})(),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37015 = all_investment_stats;var G__37015__$1 = (((G__37015 == null))?null:cljs.core.constant$keyword$964.cljs$core$IFn$_invoke$arity$1(G__37015));return G__37015__$1;
})(),cljs.core.constant$keyword$763,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__37016 = all_investment_stats;var G__37016__$1 = (((G__37016 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37016));var G__37016__$2 = (((G__37016__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37016__$1));return G__37016__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37016 = all_investment_stats;var G__37016__$1 = (((G__37016 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37016));var G__37016__$2 = (((G__37016__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37016__$1));return G__37016__$2;
})(),cljs.core.constant$keyword$813,(0),cljs.core.constant$keyword$763,"-")),(function (){var G__37017 = all_investment_stats;var G__37017__$1 = (((G__37017 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37017));var G__37017__$2 = (((G__37017__$1 == null))?null:cljs.core.constant$keyword$925.cljs$core$IFn$_invoke$arity$1(G__37017__$1));return G__37017__$2;
})(),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__37018 = all_investment_stats;var G__37018__$1 = (((G__37018 == null))?null:cljs.core.constant$keyword$967.cljs$core$IFn$_invoke$arity$1(G__37018));return G__37018__$1;
})(),cljs.core.constant$keyword$763,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__37018 = all_investment_stats;var G__37018__$1 = (((G__37018 == null))?null:cljs.core.constant$keyword$967.cljs$core$IFn$_invoke$arity$1(G__37018));return G__37018__$1;
})(),cljs.core.constant$keyword$763,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__37019 = all_investment_stats;var G__37019__$1 = (((G__37019 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37019));var G__37019__$2 = (((G__37019__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37019__$1));return G__37019__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__37019 = all_investment_stats;var G__37019__$1 = (((G__37019 == null))?null:cljs.core.constant$keyword$966.cljs$core$IFn$_invoke$arity$1(G__37019));var G__37019__$2 = (((G__37019__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37019__$1));return G__37019__$2;
})(),cljs.core.constant$keyword$811,(2),cljs.core.constant$keyword$763,"-")),(function (){var G__37020 = all_investment_stats;var G__37020__$1 = (((G__37020 == null))?null:cljs.core.constant$keyword$965.cljs$core$IFn$_invoke$arity$1(G__37020));var G__37020__$2 = (((G__37020__$1 == null))?null:cljs.core.constant$keyword$924.cljs$core$IFn$_invoke$arity$1(G__37020__$1));return G__37020__$2;
})()])], 0))], null);
});
clustermap.components.full_report.overview.pos_neg = (function pos_neg(value){if((value == null))
{return null;
} else
{if((value > (0)))
{return React.DOM.i({"className": "icon-positive"});
} else
{if((value < (0)))
{return React.DOM.i({"className": "icon-negative"});
} else
{if(true)
{return null;
} else
{return null;
}
}
}
}
});
clustermap.components.full_report.overview.overview = (function overview(data){var map__37044 = clustermap.components.full_report.overview.overview_data(data);var map__37044__$1 = ((cljs.core.seq_QMARK_(map__37044))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__37044):map__37044);var benchmark = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__37044__$1,cljs.core.constant$keyword$950);var averages = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__37044__$1,cljs.core.constant$keyword$949);var selection = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__37044__$1,cljs.core.constant$keyword$948);if(typeof clustermap.components.full_report.overview.t37045 !== 'undefined')
{} else
{
/**
* @constructor
*/
clustermap.components.full_report.overview.t37045 = (function (selection,averages,benchmark,map__37044,data,overview,meta37046){
this.selection = selection;
this.averages = averages;
this.benchmark = benchmark;
this.map__37044 = map__37044;
this.data = data;
this.overview = overview;
this.meta37046 = meta37046;
this.cljs$lang$protocol_mask$partition1$ = 0;
this.cljs$lang$protocol_mask$partition0$ = 393216;
})
clustermap.components.full_report.overview.t37045.cljs$lang$type = true;
clustermap.components.full_report.overview.t37045.cljs$lang$ctorStr = "clustermap.components.full-report.overview/t37045";
clustermap.components.full_report.overview.t37045.cljs$lang$ctorPrWriter = ((function (map__37044,map__37044__$1,benchmark,averages,selection){
return (function (this__4110__auto__,writer__4111__auto__,opt__4112__auto__){return cljs.core._write(writer__4111__auto__,"clustermap.components.full-report.overview/t37045");
});})(map__37044,map__37044__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.t37045.prototype.om$core$IRender$ = true;
clustermap.components.full_report.overview.t37045.prototype.om$core$IRender$render$arity$1 = ((function (map__37044,map__37044__$1,benchmark,averages,selection){
return (function (this__9454__auto__){var self__ = this;
var this__9454__auto____$1 = this;return React.DOM.div({"className": "full-report-overview"},React.DOM.h4(null,"Overview of latest filings",React.DOM.small(null,"\u00A0(may span years : see table below for details)")),React.DOM.div({"className": "table-responsive"},React.DOM.table({"className": "table-stats"},React.DOM.thead(null,React.DOM.tr(null,React.DOM.th(null,"\u00A0"),React.DOM.th(null,"Investor-backed companies"),React.DOM.th(null,"Investors"),React.DOM.th(null,"Constituencies"),React.DOM.th(null,"Revenue"),React.DOM.th({"colSpan": "2"},"Rev. change"),React.DOM.th(null,"Employees"))),React.DOM.tbody(null,React.DOM.tr(null,React.DOM.th(null,React.DOM.i({"className": "icon-info", "data-toggle": "tooltip", "data-container": "body", "title": (self__.selection.cljs$core$IFn$_invoke$arity$1 ? self__.selection.cljs$core$IFn$_invoke$arity$1(cljs.core.constant$keyword$951) : self__.selection.call(null,cljs.core.constant$keyword$951))}),sablono.interpreter.interpret((self__.selection.cljs$core$IFn$_invoke$arity$1 ? self__.selection.cljs$core$IFn$_invoke$arity$1(cljs.core.constant$keyword$831) : self__.selection.call(null,cljs.core.constant$keyword$831)))),React.DOM.td(null,(function (){var attrs37052 = cljs.core.constant$keyword$959.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37052))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37052], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37052))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37052)], null))));
})()),React.DOM.td(null,(function (){var attrs37053 = cljs.core.constant$keyword$956.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37053))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37053], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37053))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37053)], null))));
})()),React.DOM.td(null,(function (){var attrs37054 = cljs.core.constant$keyword$955.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37054))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37054], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37054))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37054)], null))));
})()),React.DOM.td(null,(function (){var attrs37055 = cljs.core.constant$keyword$947.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37055))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37055], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37055))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37055)], null))));
})()),React.DOM.td(null,(function (){var attrs37056 = clustermap.components.full_report.overview.pos_neg(cljs.core.constant$keyword$958.cljs$core$IFn$_invoke$arity$1(self__.selection));return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37056))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37056], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37056))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37056)], null))));
})()),React.DOM.td(null,(function (){var attrs37057 = cljs.core.constant$keyword$960.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37057))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37057], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37057))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37057)], null))));
})()),React.DOM.td(null,(function (){var attrs37058 = cljs.core.constant$keyword$954.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs37058))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$814,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs37058], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs37058))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs37058)], null))));
})()))))));
});})(map__37044,map__37044__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.t37045.prototype.cljs$core$IMeta$_meta$arity$1 = ((function (map__37044,map__37044__$1,benchmark,averages,selection){
return (function (_37047){var self__ = this;
var _37047__$1 = this;return self__.meta37046;
});})(map__37044,map__37044__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.t37045.prototype.cljs$core$IWithMeta$_with_meta$arity$2 = ((function (map__37044,map__37044__$1,benchmark,averages,selection){
return (function (_37047,meta37046__$1){var self__ = this;
var _37047__$1 = this;return (new clustermap.components.full_report.overview.t37045(self__.selection,self__.averages,self__.benchmark,self__.map__37044,self__.data,self__.overview,meta37046__$1));
});})(map__37044,map__37044__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.__GT_t37045 = ((function (map__37044,map__37044__$1,benchmark,averages,selection){
return (function __GT_t37045(selection__$1,averages__$1,benchmark__$1,map__37044__$2,data__$1,overview__$1,meta37046){return (new clustermap.components.full_report.overview.t37045(selection__$1,averages__$1,benchmark__$1,map__37044__$2,data__$1,overview__$1,meta37046));
});})(map__37044,map__37044__$1,benchmark,averages,selection))
;
}
return (new clustermap.components.full_report.overview.t37045(selection,averages,benchmark,map__37044__$1,data,overview,null));
});
