// Compiled by ClojureScript 0.0-2227
goog.provide('clustermap.components.full_report.overview');
goog.require('cljs.core');
goog.require('clustermap.formats.money');
goog.require('clustermap.formats.number');
goog.require('clustermap.formats.money');
goog.require('clustermap.formats.number');
goog.require('sablono.core');
goog.require('sablono.core');
goog.require('om.core');
goog.require('om.core');
clustermap.components.full_report.overview.describe_selection = (function describe_selection(p__34647){var map__34652 = p__34647;var map__34652__$1 = ((cljs.core.seq_QMARK_(map__34652))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__34652):map__34652);var value = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34652__$1,cljs.core.constant$keyword$583);var type = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34652__$1,cljs.core.constant$keyword$612);var pred__34653 = cljs.core._EQ_;var expr__34654 = type;if(cljs.core.truth_((pred__34653.cljs$core$IFn$_invoke$arity$2 ? pred__34653.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$698,expr__34654) : pred__34653.call(null,cljs.core.constant$keyword$698,expr__34654))))
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$761,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Total",cljs.core.constant$keyword$764,"Totals for the selected Portfolio Company"], null),cljs.core.constant$keyword$762,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Mean",cljs.core.constant$keyword$764,"Mean for the selected Portfolio Company"], null),cljs.core.constant$keyword$763,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Benchmark",cljs.core.constant$keyword$764,"Mean over all UK Companies"], null)], null);
} else
{if(cljs.core.truth_((pred__34653.cljs$core$IFn$_invoke$arity$2 ? pred__34653.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$699,expr__34654) : pred__34653.call(null,cljs.core.constant$keyword$699,expr__34654))))
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$761,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Total",cljs.core.constant$keyword$764,"Totals for the Portfolio Companies of the selected Investor"], null),cljs.core.constant$keyword$762,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Mean",cljs.core.constant$keyword$764,"Mean over the Portfolio Companies of the selected Investor"], null),cljs.core.constant$keyword$763,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Benchmark",cljs.core.constant$keyword$764,"Mean over all UK Companies"], null)], null);
} else
{if(cljs.core.truth_((pred__34653.cljs$core$IFn$_invoke$arity$2 ? pred__34653.cljs$core$IFn$_invoke$arity$2(cljs.core.constant$keyword$701,expr__34654) : pred__34653.call(null,cljs.core.constant$keyword$701,expr__34654))))
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$761,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Total",cljs.core.constant$keyword$764,"Totals for the selected Constituency"], null),cljs.core.constant$keyword$762,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Mean",cljs.core.constant$keyword$764,"Mean over the Portfolio Companies with sites in the selected Constituency"], null),cljs.core.constant$keyword$763,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Benchmark",cljs.core.constant$keyword$764,"Mean over all UK Companies"], null)], null);
} else
{return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$761,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Total",cljs.core.constant$keyword$764,"Totals over all Portfolio Companies"], null),cljs.core.constant$keyword$762,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Mean",cljs.core.constant$keyword$764,"Mean over all Portfolio Companies"], null),cljs.core.constant$keyword$763,new cljs.core.PersistentArrayMap(null, 2, [cljs.core.constant$keyword$643,"Benchmark",cljs.core.constant$keyword$764,"Mean over all UK Companies"], null)], null);
}
}
}
});
clustermap.components.full_report.overview.overview_data = (function overview_data(p__34656){var map__34682 = p__34656;var map__34682__$1 = ((cljs.core.seq_QMARK_(map__34682))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__34682):map__34682);var selection_investment_stats = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34682__$1,cljs.core.constant$keyword$765);var selection = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34682__$1,cljs.core.constant$keyword$761);var all_investment_stats = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34682__$1,cljs.core.constant$keyword$766);var sel_descrs = clustermap.components.full_report.overview.describe_selection(selection);var site_stats = (function (){var or__3539__auto__ = selection_investment_stats;if(cljs.core.truth_(or__3539__auto__))
{return or__3539__auto__;
} else
{return all_investment_stats;
}
})();return new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$761,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$761.cljs$core$IFn$_invoke$arity$1(sel_descrs),cljs.core.PersistentHashMap.fromArrays([cljs.core.constant$keyword$767,cljs.core.constant$keyword$768,cljs.core.constant$keyword$760,cljs.core.constant$keyword$769,cljs.core.constant$keyword$770,cljs.core.constant$keyword$771,cljs.core.constant$keyword$772,cljs.core.constant$keyword$773,cljs.core.constant$keyword$774],[(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__34683 = site_stats;var G__34683__$1 = (((G__34683 == null))?null:cljs.core.constant$keyword$775.cljs$core$IFn$_invoke$arity$1(G__34683));var G__34683__$2 = (((G__34683__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34683__$1));return G__34683__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34683 = site_stats;var G__34683__$1 = (((G__34683 == null))?null:cljs.core.constant$keyword$775.cljs$core$IFn$_invoke$arity$1(G__34683));var G__34683__$2 = (((G__34683__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34683__$1));return G__34683__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__34684 = site_stats;var G__34684__$1 = (((G__34684 == null))?null:cljs.core.constant$keyword$776.cljs$core$IFn$_invoke$arity$1(G__34684));return G__34684__$1;
})(),cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34684 = site_stats;var G__34684__$1 = (((G__34684 == null))?null:cljs.core.constant$keyword$776.cljs$core$IFn$_invoke$arity$1(G__34684));return G__34684__$1;
})(),cljs.core.constant$keyword$579,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__34685 = site_stats;var G__34685__$1 = (((G__34685 == null))?null:cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(G__34685));var G__34685__$2 = (((G__34685__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34685__$1));return G__34685__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__34685 = site_stats;var G__34685__$1 = (((G__34685 == null))?null:cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(G__34685));var G__34685__$2 = (((G__34685__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34685__$1));return G__34685__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__34686 = site_stats;var G__34686__$1 = (((G__34686 == null))?null:cljs.core.constant$keyword$777.cljs$core$IFn$_invoke$arity$1(G__34686));return G__34686__$1;
})(),cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34686 = site_stats;var G__34686__$1 = (((G__34686 == null))?null:cljs.core.constant$keyword$777.cljs$core$IFn$_invoke$arity$1(G__34686));return G__34686__$1;
})(),cljs.core.constant$keyword$579,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__34687 = site_stats;var G__34687__$1 = (((G__34687 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34687));var G__34687__$2 = (((G__34687__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34687__$1));return G__34687__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34687 = site_stats;var G__34687__$1 = (((G__34687 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34687));var G__34687__$2 = (((G__34687__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34687__$1));return G__34687__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-")),(function (){var G__34688 = site_stats;var G__34688__$1 = (((G__34688 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34688));var G__34688__$2 = (((G__34688__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34688__$1));return G__34688__$2;
})(),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__34689 = site_stats;var G__34689__$1 = (((G__34689 == null))?null:cljs.core.constant$keyword$780.cljs$core$IFn$_invoke$arity$1(G__34689));return G__34689__$1;
})(),cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34689 = site_stats;var G__34689__$1 = (((G__34689 == null))?null:cljs.core.constant$keyword$780.cljs$core$IFn$_invoke$arity$1(G__34689));return G__34689__$1;
})(),cljs.core.constant$keyword$579,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__34690 = site_stats;var G__34690__$1 = (((G__34690 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34690));var G__34690__$2 = (((G__34690__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34690__$1));return G__34690__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__34690 = site_stats;var G__34690__$1 = (((G__34690 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34690));var G__34690__$2 = (((G__34690__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34690__$1));return G__34690__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-")),(function (){var G__34691 = site_stats;var G__34691__$1 = (((G__34691 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34691));var G__34691__$2 = (((G__34691__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34691__$1));return G__34691__$2;
})()])], 0)),cljs.core.constant$keyword$762,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$762.cljs$core$IFn$_invoke$arity$1(sel_descrs),cljs.core.PersistentHashMap.fromArrays([cljs.core.constant$keyword$767,cljs.core.constant$keyword$768,cljs.core.constant$keyword$760,cljs.core.constant$keyword$769,cljs.core.constant$keyword$770,cljs.core.constant$keyword$771,cljs.core.constant$keyword$772,cljs.core.constant$keyword$773,cljs.core.constant$keyword$774],[(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__34692 = site_stats;var G__34692__$1 = (((G__34692 == null))?null:cljs.core.constant$keyword$775.cljs$core$IFn$_invoke$arity$1(G__34692));var G__34692__$2 = (((G__34692__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34692__$1));return G__34692__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34692 = site_stats;var G__34692__$1 = (((G__34692 == null))?null:cljs.core.constant$keyword$775.cljs$core$IFn$_invoke$arity$1(G__34692));var G__34692__$2 = (((G__34692__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34692__$1));return G__34692__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-")),"\u00A0",(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__34693 = site_stats;var G__34693__$1 = (((G__34693 == null))?null:cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(G__34693));var G__34693__$2 = (((G__34693__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34693__$1));return G__34693__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__34693 = site_stats;var G__34693__$1 = (((G__34693 == null))?null:cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(G__34693));var G__34693__$2 = (((G__34693__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34693__$1));return G__34693__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-")),"\u00A0",(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__34694 = site_stats;var G__34694__$1 = (((G__34694 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34694));var G__34694__$2 = (((G__34694__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34694__$1));return G__34694__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34694 = site_stats;var G__34694__$1 = (((G__34694 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34694));var G__34694__$2 = (((G__34694__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34694__$1));return G__34694__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-")),(function (){var G__34695 = site_stats;var G__34695__$1 = (((G__34695 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34695));var G__34695__$2 = (((G__34695__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34695__$1));return G__34695__$2;
})(),"\u00A0",(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__34696 = site_stats;var G__34696__$1 = (((G__34696 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34696));var G__34696__$2 = (((G__34696__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34696__$1));return G__34696__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__34696 = site_stats;var G__34696__$1 = (((G__34696 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34696));var G__34696__$2 = (((G__34696__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34696__$1));return G__34696__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-")),(function (){var G__34697 = site_stats;var G__34697__$1 = (((G__34697 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34697));var G__34697__$2 = (((G__34697__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34697__$1));return G__34697__$2;
})()])], 0)),cljs.core.constant$keyword$763,cljs.core.merge.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([cljs.core.constant$keyword$763.cljs$core$IFn$_invoke$arity$1(sel_descrs),cljs.core.PersistentHashMap.fromArrays([cljs.core.constant$keyword$767,cljs.core.constant$keyword$768,cljs.core.constant$keyword$760,cljs.core.constant$keyword$769,cljs.core.constant$keyword$770,cljs.core.constant$keyword$771,cljs.core.constant$keyword$772,cljs.core.constant$keyword$773,cljs.core.constant$keyword$774],[(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__34698 = all_investment_stats;var G__34698__$1 = (((G__34698 == null))?null:cljs.core.constant$keyword$775.cljs$core$IFn$_invoke$arity$1(G__34698));var G__34698__$2 = (((G__34698__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34698__$1));return G__34698__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34698 = all_investment_stats;var G__34698__$1 = (((G__34698 == null))?null:cljs.core.constant$keyword$775.cljs$core$IFn$_invoke$arity$1(G__34698));var G__34698__$2 = (((G__34698__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34698__$1));return G__34698__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__34699 = all_investment_stats;var G__34699__$1 = (((G__34699 == null))?null:cljs.core.constant$keyword$776.cljs$core$IFn$_invoke$arity$1(G__34699));return G__34699__$1;
})(),cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34699 = all_investment_stats;var G__34699__$1 = (((G__34699 == null))?null:cljs.core.constant$keyword$776.cljs$core$IFn$_invoke$arity$1(G__34699));return G__34699__$1;
})(),cljs.core.constant$keyword$579,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__34700 = all_investment_stats;var G__34700__$1 = (((G__34700 == null))?null:cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(G__34700));var G__34700__$2 = (((G__34700__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34700__$1));return G__34700__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__34700 = all_investment_stats;var G__34700__$1 = (((G__34700 == null))?null:cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(G__34700));var G__34700__$2 = (((G__34700__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34700__$1));return G__34700__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__34701 = all_investment_stats;var G__34701__$1 = (((G__34701 == null))?null:cljs.core.constant$keyword$777.cljs$core$IFn$_invoke$arity$1(G__34701));return G__34701__$1;
})(),cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34701 = all_investment_stats;var G__34701__$1 = (((G__34701 == null))?null:cljs.core.constant$keyword$777.cljs$core$IFn$_invoke$arity$1(G__34701));return G__34701__$1;
})(),cljs.core.constant$keyword$579,"-")),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$5((function (){var G__34702 = all_investment_stats;var G__34702__$1 = (((G__34702 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34702));var G__34702__$2 = (((G__34702__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34702__$1));return G__34702__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34702 = all_investment_stats;var G__34702__$1 = (((G__34702 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34702));var G__34702__$2 = (((G__34702__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34702__$1));return G__34702__$2;
})(),cljs.core.constant$keyword$624,0,cljs.core.constant$keyword$579,"-")),(function (){var G__34703 = all_investment_stats;var G__34703__$1 = (((G__34703 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34703));var G__34703__$2 = (((G__34703__$1 == null))?null:cljs.core.constant$keyword$738.cljs$core$IFn$_invoke$arity$1(G__34703__$1));return G__34703__$2;
})(),(clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3 ? clustermap.formats.number.fnum.cljs$core$IFn$_invoke$arity$3((function (){var G__34704 = all_investment_stats;var G__34704__$1 = (((G__34704 == null))?null:cljs.core.constant$keyword$780.cljs$core$IFn$_invoke$arity$1(G__34704));return G__34704__$1;
})(),cljs.core.constant$keyword$579,"-") : clustermap.formats.number.fnum.call(null,(function (){var G__34704 = all_investment_stats;var G__34704__$1 = (((G__34704 == null))?null:cljs.core.constant$keyword$780.cljs$core$IFn$_invoke$arity$1(G__34704));return G__34704__$1;
})(),cljs.core.constant$keyword$579,"-")),(clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5 ? clustermap.formats.money.fmoney.cljs$core$IFn$_invoke$arity$5((function (){var G__34705 = all_investment_stats;var G__34705__$1 = (((G__34705 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34705));var G__34705__$2 = (((G__34705__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34705__$1));return G__34705__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-") : clustermap.formats.money.fmoney.call(null,(function (){var G__34705 = all_investment_stats;var G__34705__$1 = (((G__34705 == null))?null:cljs.core.constant$keyword$779.cljs$core$IFn$_invoke$arity$1(G__34705));var G__34705__$2 = (((G__34705__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34705__$1));return G__34705__$2;
})(),cljs.core.constant$keyword$622,2,cljs.core.constant$keyword$579,"-")),(function (){var G__34706 = all_investment_stats;var G__34706__$1 = (((G__34706 == null))?null:cljs.core.constant$keyword$778.cljs$core$IFn$_invoke$arity$1(G__34706));var G__34706__$2 = (((G__34706__$1 == null))?null:cljs.core.constant$keyword$737.cljs$core$IFn$_invoke$arity$1(G__34706__$1));return G__34706__$2;
})()])], 0))], null);
});
clustermap.components.full_report.overview.pos_neg = (function pos_neg(value){if((value == null))
{return null;
} else
{if((value > 0))
{return React.DOM.i({"className": "icon-positive"});
} else
{if((value < 0))
{return React.DOM.i({"className": "icon-negative"});
} else
{if(true)
{return null;
} else
{return null;
}
}
}
}
});
clustermap.components.full_report.overview.overview = (function overview(data){var map__34730 = clustermap.components.full_report.overview.overview_data(data);var map__34730__$1 = ((cljs.core.seq_QMARK_(map__34730))?cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.hash_map,map__34730):map__34730);var benchmark = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34730__$1,cljs.core.constant$keyword$763);var averages = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34730__$1,cljs.core.constant$keyword$762);var selection = cljs.core.get.cljs$core$IFn$_invoke$arity$2(map__34730__$1,cljs.core.constant$keyword$761);if(typeof clustermap.components.full_report.overview.t34731 !== 'undefined')
{} else
{
/**
* @constructor
*/
clustermap.components.full_report.overview.t34731 = (function (selection,averages,benchmark,map__34730,data,overview,meta34732){
this.selection = selection;
this.averages = averages;
this.benchmark = benchmark;
this.map__34730 = map__34730;
this.data = data;
this.overview = overview;
this.meta34732 = meta34732;
this.cljs$lang$protocol_mask$partition1$ = 0;
this.cljs$lang$protocol_mask$partition0$ = 393216;
})
clustermap.components.full_report.overview.t34731.cljs$lang$type = true;
clustermap.components.full_report.overview.t34731.cljs$lang$ctorStr = "clustermap.components.full-report.overview/t34731";
clustermap.components.full_report.overview.t34731.cljs$lang$ctorPrWriter = ((function (map__34730,map__34730__$1,benchmark,averages,selection){
return (function (this__4106__auto__,writer__4107__auto__,opt__4108__auto__){return cljs.core._write(writer__4107__auto__,"clustermap.components.full-report.overview/t34731");
});})(map__34730,map__34730__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.t34731.prototype.om$core$IRender$ = true;
clustermap.components.full_report.overview.t34731.prototype.om$core$IRender$render$arity$1 = ((function (map__34730,map__34730__$1,benchmark,averages,selection){
return (function (this__9410__auto__){var self__ = this;
var this__9410__auto____$1 = this;return React.DOM.div({"className": "full-report-overview"},React.DOM.h4(null,"Overview of latest filings",React.DOM.small(null,"\u00A0(may span years : see table below for details)")),React.DOM.div({"className": "table-responsive"},React.DOM.table({"className": "table-stats"},React.DOM.thead(null,React.DOM.tr(null,React.DOM.th(null,"\u00A0"),React.DOM.th(null,"Investor-backed companies"),React.DOM.th(null,"Investors"),React.DOM.th(null,"Constituencies"),React.DOM.th(null,"Revenue"),React.DOM.th({"colSpan": "2"},"Rev. change"),React.DOM.th(null,"Employees"))),React.DOM.tbody(null,React.DOM.tr(null,React.DOM.th(null,React.DOM.i({"className": "icon-info", "data-toggle": "tooltip", "data-container": "body", "title": (self__.selection.cljs$core$IFn$_invoke$arity$1 ? self__.selection.cljs$core$IFn$_invoke$arity$1(cljs.core.constant$keyword$764) : self__.selection.call(null,cljs.core.constant$keyword$764))}),sablono.interpreter.interpret((self__.selection.cljs$core$IFn$_invoke$arity$1 ? self__.selection.cljs$core$IFn$_invoke$arity$1(cljs.core.constant$keyword$643) : self__.selection.call(null,cljs.core.constant$keyword$643)))),React.DOM.td(null,(function (){var attrs34738 = cljs.core.constant$keyword$772.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34738))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34738], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34738))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34738)], null))));
})()),React.DOM.td(null,(function (){var attrs34739 = cljs.core.constant$keyword$769.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34739))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34739], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34739))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34739)], null))));
})()),React.DOM.td(null,(function (){var attrs34740 = cljs.core.constant$keyword$768.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34740))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34740], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34740))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34740)], null))));
})()),React.DOM.td(null,(function (){var attrs34741 = cljs.core.constant$keyword$760.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34741))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34741], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34741))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34741)], null))));
})()),React.DOM.td(null,(function (){var attrs34742 = clustermap.components.full_report.overview.pos_neg(cljs.core.constant$keyword$771.cljs$core$IFn$_invoke$arity$1(self__.selection));return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34742))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34742], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34742))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34742)], null))));
})()),React.DOM.td(null,(function (){var attrs34743 = cljs.core.constant$keyword$773.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34743))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34743], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34743))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34743)], null))));
})()),React.DOM.td(null,(function (){var attrs34744 = cljs.core.constant$keyword$767.cljs$core$IFn$_invoke$arity$1(self__.selection);return cljs.core.apply.cljs$core$IFn$_invoke$arity$3(React.DOM.span,((cljs.core.map_QMARK_(attrs34744))?sablono.interpreter.attributes(sablono.util.merge_with_class.cljs$core$IFn$_invoke$arity$variadic(cljs.core.array_seq([new cljs.core.PersistentArrayMap(null, 1, [cljs.core.constant$keyword$625,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, ["selection"], null)], null),attrs34744], 0))):{"className": "selection"}),cljs.core.remove(cljs.core.nil_QMARK_,((cljs.core.map_QMARK_(attrs34744))?cljs.core.PersistentVector.EMPTY:new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [sablono.interpreter.interpret(attrs34744)], null))));
})()))))));
});})(map__34730,map__34730__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.t34731.prototype.cljs$core$IMeta$_meta$arity$1 = ((function (map__34730,map__34730__$1,benchmark,averages,selection){
return (function (_34733){var self__ = this;
var _34733__$1 = this;return self__.meta34732;
});})(map__34730,map__34730__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.t34731.prototype.cljs$core$IWithMeta$_with_meta$arity$2 = ((function (map__34730,map__34730__$1,benchmark,averages,selection){
return (function (_34733,meta34732__$1){var self__ = this;
var _34733__$1 = this;return (new clustermap.components.full_report.overview.t34731(self__.selection,self__.averages,self__.benchmark,self__.map__34730,self__.data,self__.overview,meta34732__$1));
});})(map__34730,map__34730__$1,benchmark,averages,selection))
;
clustermap.components.full_report.overview.__GT_t34731 = ((function (map__34730,map__34730__$1,benchmark,averages,selection){
return (function __GT_t34731(selection__$1,averages__$1,benchmark__$1,map__34730__$2,data__$1,overview__$1,meta34732){return (new clustermap.components.full_report.overview.t34731(selection__$1,averages__$1,benchmark__$1,map__34730__$2,data__$1,overview__$1,meta34732));
});})(map__34730,map__34730__$1,benchmark,averages,selection))
;
}
return (new clustermap.components.full_report.overview.t34731(selection,averages,benchmark,map__34730__$1,data,overview,null));
});
