// Compiled by ClojureScript 0.0-2080
goog.provide('clustermap.nav');
goog.require('cljs.core');
goog.require('cljs.core.async');
goog.require('jayq.core');
goog.require('domina.events');
goog.require('domina.events');
goog.require('domina');
goog.require('domina.xpath');
goog.require('domina');
goog.require('domina.css');
goog.require('cljs.core.async');
goog.require('domina.css');
goog.require('domina.xpath');
goog.require('jayq.core');
clustermap.nav.toggle_nav_search = (function toggle_nav_search(){return domina.events.listen_BANG_.cljs$core$IFn$_invoke$arity$3(domina.css.sel.cljs$core$IFn$_invoke$arity$1("#nav .search > a"),cljs.core.constant$keyword$112,(function (e){domina.events.prevent_default(e);
alert("woop");
var target = domina.events.target(e);var parent = domina.xpath.xpath.cljs$core$IFn$_invoke$arity$2(target,"..");domina.toggle_class_BANG_(parent,"open");
return jayq.core.$.cljs$core$IFn$_invoke$arity$1(cljs.core.first(domina.css.sel.cljs$core$IFn$_invoke$arity$1("#search").domina$DomContent$nodes$arity$1(null))).toggle();
}));
});
clustermap.nav.switch_view = (function switch_view(){return domina.events.listen_BANG_.cljs$core$IFn$_invoke$arity$3(domina.css.sel.cljs$core$IFn$_invoke$arity$1("#nav .map > a, #nav .lists > a"),cljs.core.constant$keyword$112,(function (e){domina.events.prevent_default(e);
var target = domina.events.target(e);var li = domina.xpath.xpath.cljs$core$IFn$_invoke$arity$2(target,"..");var ul = domina.xpath.xpath.cljs$core$IFn$_invoke$arity$2(li,"..");var active_li = domina.css.sel.cljs$core$IFn$_invoke$arity$2(ul,"> .active");domina.remove_class_BANG_(active_li,"active");
return domina.add_class_BANG_(li,"active");
}));
});
clustermap.nav.init = (function init(){clustermap.nav.toggle_nav_search();
return clustermap.nav.switch_view();
});
