// Compiled by ClojureScript 0.0-2138
goog.provide('clustermap.routes');
goog.require('cljs.core');
goog.require('sablono.core');
goog.require('sablono.core');
goog.require('sablono.core');
clustermap.routes.type_name_keys = new cljs.core.PersistentArrayMap(null, 3, [cljs.core.constant$keyword$297,cljs.core.constant$keyword$274,cljs.core.constant$keyword$298,cljs.core.constant$keyword$274,cljs.core.constant$keyword$299,cljs.core.constant$keyword$380], null);
clustermap.routes.name_for = (function name_for(type,obj){return cljs.core.get.cljs$core$IFn$_invoke$arity$2(obj,cljs.core.get.cljs$core$IFn$_invoke$arity$2(clustermap.routes.type_name_keys,type));
});
clustermap.routes.portfolio_company_path = (function portfolio_company_path(app_state,obj){return [cljs.core.str("#/"),cljs.core.str((function (){var G__23023 = app_state;var G__23023__$1 = (((G__23023 == null))?null:cljs.core.deref(G__23023));var G__23023__$2 = (((G__23023__$1 == null))?null:cljs.core.constant$keyword$381.cljs$core$IFn$_invoke$arity$1(G__23023__$1));var G__23023__$3 = (((G__23023__$2 == null))?null:cljs.core.name(G__23023__$2));return G__23023__$3;
})()),cljs.core.str("/portfolio-company/"),cljs.core.str(cljs.core.constant$keyword$382.cljs$core$IFn$_invoke$arity$1(obj))].join('');
});
clustermap.routes.investor_company_path = (function investor_company_path(app_state,obj){return [cljs.core.str("#/"),cljs.core.str((function (){var G__23025 = app_state;var G__23025__$1 = (((G__23025 == null))?null:cljs.core.deref(G__23025));var G__23025__$2 = (((G__23025__$1 == null))?null:cljs.core.constant$keyword$381.cljs$core$IFn$_invoke$arity$1(G__23025__$1));var G__23025__$3 = (((G__23025__$2 == null))?null:cljs.core.name(G__23025__$2));return G__23025__$3;
})()),cljs.core.str("/investor-company/"),cljs.core.str(cljs.core.constant$keyword$383.cljs$core$IFn$_invoke$arity$1(obj))].join('');
});
clustermap.routes.constituency_path = (function constituency_path(app_state,obj){return [cljs.core.str("#/"),cljs.core.str((function (){var G__23027 = app_state;var G__23027__$1 = (((G__23027 == null))?null:cljs.core.deref(G__23027));var G__23027__$2 = (((G__23027__$1 == null))?null:cljs.core.constant$keyword$381.cljs$core$IFn$_invoke$arity$1(G__23027__$1));var G__23027__$3 = (((G__23027__$2 == null))?null:cljs.core.name(G__23027__$2));return G__23027__$3;
})()),cljs.core.str("/constituency/"),cljs.core.str(cljs.core.constant$keyword$384.cljs$core$IFn$_invoke$arity$1(obj))].join('');
});
clustermap.routes.no_selection_path = (function no_selection_path(app_state,_){return [cljs.core.str("#/"),cljs.core.str((function (){var G__23029 = app_state;var G__23029__$1 = (((G__23029 == null))?null:cljs.core.deref(G__23029));var G__23029__$2 = (((G__23029__$1 == null))?null:cljs.core.constant$keyword$381.cljs$core$IFn$_invoke$arity$1(G__23029__$1));var G__23029__$3 = (((G__23029__$2 == null))?null:cljs.core.name(G__23029__$2));return G__23029__$3;
})())].join('');
});
clustermap.routes.type_paths = new cljs.core.PersistentArrayMap(null, 4, [cljs.core.constant$keyword$297,clustermap.routes.portfolio_company_path,cljs.core.constant$keyword$298,clustermap.routes.investor_company_path,cljs.core.constant$keyword$299,clustermap.routes.constituency_path,null,clustermap.routes.no_selection_path], null);
clustermap.routes.path_for = (function path_for(app_state,type,obj){return cljs.core.apply.cljs$core$IFn$_invoke$arity$2(cljs.core.get.cljs$core$IFn$_invoke$arity$2(clustermap.routes.type_paths,type),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [app_state,obj], null));
});
clustermap.routes.link_for = (function link_for(app_state,type,obj){return React.DOM.a({"href": clustermap.routes.path_for(app_state,type,obj)},sablono.interpreter.interpret(clustermap.routes.name_for(type,obj)));
});
